services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Expose NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount NGINX config
    depends_on:
      - mindsdb
    networks:
      - mindsdb_network

  mindsdb:
    image: mindsdb/mindsdb:latest
    container_name: mindsdb
    expose:
      - "47334"
      - "47335"
      - "47336"
    volumes:
      - data:/opt/mindsdb/data
      - config:/opt/mindsdb/config
    networks:
      - mindsdb_network

volumes:
  data:
  config:

networks:
  mindsdb_network:
    driver: bridge
